{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "qdrant.fullname" . }}
  labels:
    {{- include "qdrant.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "qdrant.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  {{- toYaml .Values.networkPolicy.ingress | nindent 2 }}
{{- end }}
