{{- if .Values.ingressRoute.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "docs-site.fullname" . }}
  labels:
    {{- include "docs-site.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- toYaml .Values.ingressRoute.entryPoints | nindent 4 }}
  routes:
    - match: Host(`{{ .Values.ingressRoute.host }}`)
      kind: Rule
      {{- if .Values.ingressRoute.middlewares }}
      middlewares:
        {{- toYaml .Values.ingressRoute.middlewares | nindent 8 }}
      {{- end }}
      services:
        - name: {{ include "docs-site.fullname" . }}
          port: {{ .Values.service.port }}
  {{- if .Values.ingressRoute.tls }}
  tls:
    {{- toYaml .Values.ingressRoute.tls | nindent 4 }}
  {{- end }}
{{- end }}
