{{- if .Values.audio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "self-hosted-ai-gpu-worker.fullname" . }}-audio
  labels:
    app.kubernetes.io/name: {{ include "self-hosted-ai-gpu-worker.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: audio
spec:
  type: {{ .Values.audio.service.type }}
  ports:
    - port: {{ .Values.audio.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "self-hosted-ai-gpu-worker.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: audio
{{- end }}
