{{- if .Values.comfyui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "self-hosted-ai-gpu-worker.fullname" . }}-comfyui
  labels:
    app.kubernetes.io/name: {{ include "self-hosted-ai-gpu-worker.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: comfyui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "self-hosted-ai-gpu-worker.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: comfyui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "self-hosted-ai-gpu-worker.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/component: comfyui
    spec:
      {{- with .Values.comfyui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.comfyui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: comfyui
          image: "{{ .Values.comfyui.image.repository }}:{{ .Values.comfyui.image.tag }}"
          imagePullPolicy: {{ .Values.comfyui.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8188
              protocol: TCP
          env:
            {{- range .Values.comfyui.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          volumeMounts:
            - name: data
              mountPath: /comfyui
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            {{- toYaml .Values.comfyui.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "self-hosted-ai-gpu-worker.fullname" . }}-comfyui
{{- end }}