{{- if and .Values.comfyui.enabled .Values.comfyui.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "self-hosted-ai-gpu-worker.fullname" . }}-comfyui
  labels:
    app.kubernetes.io/name: {{ include "self-hosted-ai-gpu-worker.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: comfyui
  {{- with .Values.comfyui.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.comfyui.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.comfyui.persistence.size }}
  {{- if .Values.comfyui.persistence.storageClass }}
  storageClassName: {{ .Values.comfyui.persistence.storageClass }}
  {{- end }}
{{- end }}