{{- if .Values.tts.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "self-hosted-ai-gpu-worker.fullname" . }}-tts
  labels:
    app.kubernetes.io/name: {{ include "self-hosted-ai-gpu-worker.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: tts
spec:
  type: {{ .Values.tts.service.type }}
  ports:
    - port: {{ .Values.tts.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "self-hosted-ai-gpu-worker.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: tts
{{- end }}
