{{- if .Values.video.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "self-hosted-ai-gpu-worker.fullname" . }}-video
  labels:
    app.kubernetes.io/name: {{ include "self-hosted-ai-gpu-worker.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: video
spec:
  type: {{ .Values.video.service.type }}
  ports:
    - port: {{ .Values.video.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "self-hosted-ai-gpu-worker.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: video
{{- end }}
