apiVersion: v1
kind: Service
metadata:
  name: {{ include "jaeger.fullname" . }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $name, $port := .Values.service.ports }}
    - port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
      protocol: {{ $port.protocol }}
      name: {{ $name }}
    {{- end }}
  selector:
    {{- include "jaeger.selectorLabels" . | nindent 4 }}
