{{- if .Values.imageRouter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "self-hosted-ai-server.fullname" . }}-image-router
  labels:
    {{- include "self-hosted-ai-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: image-router
  {{- with .Values.imageRouter.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.imageRouter.service.type }}
  ports:
    - port: {{ .Values.imageRouter.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "self-hosted-ai-server.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: image-router
{{- end }}