apiVersion: v2
name: loki
description: Grafana Loki log aggregation for Kubernetes
type: application
version: 1.0.0
appVersion: "3.0.0"

dependencies:
  - name: loki
    version: 6.22.0
    repository: https://grafana.github.io/helm-charts
  - name: promtail
    version: 6.19.0
    repository: https://grafana.github.io/helm-charts
